### ISSUE TITLE
Javascript Error not allowing entry edit

### ISSUE THREAD

**Issue by john-henry** [Anubarak/craft-relabel#3]
I am getting a Javascript error when editing entries with Relabel 1.1.6 and Craft CMS 3.0.35

http://cloud.johnhenry.ie/6a8f0fd07a79

The entry has multiple Entry Types and has matrix fields with multiple blocks. I am unable to add any rows to matrix with this error

**Comment by john-henry** [comment]
Same goes for entries with single Entry type

**Comment by Anubarak** [comment]
Thanks for notifying me - unfortunately I was not really able to reproduce it but I included additional checks to see if the variable is null or not. (It should actually not even be null in the first place since I only grab the label `<span>` that should never be `null`)

If it still happens please contact me. Do you have any other plugins installed or some things that might change your default HTML?

**Comment by john-henry** [comment]
I had Matrix Colors which may have affected that?

**Comment by Anubarak** [comment]
That should not be the case, it just adds classes but it doesn't remove the default one. I installed it but it still worked for me. 
If it happens again after my update yesterday (if you didn't already uninstalled Relabel) please report it
