### ISSUE TITLE
Not working with Solspace Calendar plugin

### ISSUE THREAD

**Issue by KatieMFritz** [Anubarak/craft-relabel#8]
First of all, thanks for this plugin! It makes managing fields a lot easier. 🎉 

I'm using the [Solspace Calendar](https://github.com/solspace/craft3-calendar) plugin, and while I'm able to change labels when I'm setting up my fields for each calendar, the new labels don't display when adding/editing an entry.

I see in your docs that you don't officially support Solspace events yet. Is this something that Solspace can add support for on their end? If so, what can I tell them? Thanks!

**Comment by Anubarak** [comment]
Usually that's part of the other plugins since I provide more than enough possibilities to include support for the plugin but I did it for you.
I don't know the plugin and never used it so chances are high I forgot a hidden field layout I wasn't able to track please let me know if everything is okay for you now

**Comment by KatieMFritz** [comment]
Hey, that works now! 🎉 You've been helping me all over the place this week. 😄
