### ISSUE TITLE
Empty label not falling back to default label

### ISSUE THREAD

**Issue by timeverts** [Anubarak/craft-relabel#9]
For the Relabel options on a field, if I do not specify a value for 'New Label' in the HUD, when the field is rendered it is rendered without a label. I would have thought that if no label is specified in the HUD, then when the field is rendered it should fall back to using the field's default label.

**Comment by architchandra** [comment]
I just faced the same problem for the description.

**Comment by Anubarak** [comment]
I don't think it's useful to fall back to the default description. You don't really want to have a blank label, but when you use another name for the field usually the description does not fit anymore or you want to have the possibility to change it.

Falling back to the default description would "break" many of my projects since I rely on "removing" the description by storing a blank one (this is my default setup).
I could include a config setting via PHP file that you can turn on "use description fallback if it's blank" if that's okay for you.

**Comment by architchandra** [comment]
Yes, that would be a good step.
